baseurl                 = "https://jay.rbind.io"
DefaultContentLanguage  = "en"
title                   = "Jay Achar"
theme                   = "hugo-future-imperfect-slim"
preserveTaxonomyNames   = true
paginate                = 3
disqusShortname         = ""
googleAnalytics         = "UA-128985004-3"
pluralizeListTitles     = false
disableLanguages        = [""]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  author = "Jay Achar"
  mainSections = ["blog", "post"]
  # Loads CSS and JavaScript files. The variable is an array so that you can load
  # multiple/additional files if necessary. The standard theme files can be loaded
  # by adding the value, "default". Default includes the add-on.css and and-on.js.
  # Example: ["default", "/path/to/file"]
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  # Sets options for highlight.js
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml", "r"]
  # Sets where "View More Posts" links to
  viewMorePostsLink     = "/post/"
  # Activate Estimated Reading Times, which appear in the post headers
  readingTime           = true
  # Sets which Social Share links appear in posts.
  # Options are twitter, facebook, reddit, linkedin, pinterest, email
  socialShare           = ["twitter", "facebook", "reddit", "linkedin",
                          "pinterest", "email"]

  [params.meta]
    # Sets the meta tag description
    description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
    # Sets the meta tag author
    author              = "HTML5UP and Hugo"
    # If you would like to add more comprehensive favicon support passed root
    # directory favicon.ico, utlize this funtion. It is recommened to use
    # https://realfavicongenerator.net to generate your icons as that is the basis
    # for the theme's naming.
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff" # Copy from the https://realfavicongenerator.net
    iOSColor            = "#ffffff" # Copy from the https://realfavicongenerator.net

  [params.header]
    # Sets the navbarTitle that appears in the top left of the navigation bar
    navbarTitle         = "Jay Achar"
    # Sets navbarTitle to match the section of the website
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
  [params.intro]
    header                = "Jay Achar"
    paragraph             = "Infectious Diseases Specialist<br>Tuberculosis, HIV, Global Health<br>Data driven"
    rssIntro              = false
    socialIntro           = true

    # This appears at the top of the sidebar above params.intro.header.
    # A width of less than 100px is recommended from a design perspective.
    [params.intro.pic]
      src                 = "/img/low_res_headshot.jpg"
      # Masks image in a certain shape. Supported are circle, triangle, diamond, and hexagon.
      shape               = "circle"
      width               = "100px"
      alt                 = "Jay Achar"

  [params.sidebar]
    about               = "I'm an Infectious Diseases specialist doctor and epidemiologist with keen interests in tuberculosis, data-driven programming and research."
    # Sets the number of recent posts to show in the sidebar. The default value is 5.
    postAmount          = 5
    # set to show or to hide categories in the sidebar
    categories          = true
    # Sets Categories to sort by number of posts instead of alphabetical
    categoriesByCount   = true

  [params.footer]
    # Sets RSS icons to appear on the sidebar with the social media buttons
    rssFooter           = false
    # Sets Social Media icons to appear on the sidebar
    socialFooter        = true

  # Disqus will take priority over Staticman (github.com/eduardoboucas/staticman)
  # due to its ease of use. Feel free to check out both and decide which you would
  # prefer to use. See staticman.yml for additional settings.
  [params.staticman]
    # If using GitHub, go to https://github.com/apps/staticman-net
    # If using GitLab, just add the GitLab bot, NO need to hit `/connect/v3/...`
    enabled             = false
    api                 = ""  # without trailing slash, defaults to "staticman3.herokuapp.com"
    gitProvider         = "github"  # either "github" or "gitlab"
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      # Both keys must be present to enable recaptcha
      siteKey           = "" # Site Key
      encryptedKey      = ""

[menu]
  # Sets the menu items in the navigation bar
  # Identifier prepends a Font Awesome icon to the menu item
  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "CV"
    identifier        = "cv"
    url               = "/cv/"
    pre               = "<i class='fas fa-scroll'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/post/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 4

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 5

[Languages]
  # Each language has its own menu.
  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Coding Communities
  github                = "JayAchar"
  gitlab                = ""
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "jay-achar-666a7611a/"
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  googlescholar         = ""
  orcid                 = "0000-0002-2521-4422"
  researchgate          = "Jay_Achar"
  # Social Networks
  facebook              = ""
  googleplus            = ""
  reddit                = ""
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = "jay_achar"
  tumblr                = ""
  twitter               = "dr_jay_a"
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  keybase               = ""
  mastodon              = ""
  # Email
  email                 = "jay.achar@doctors.org.uk?subject:Website_enquiry"
