baseurl = "https://jayachar.rbind.io/"
title = "Jay Achar"

theme = "hugo-coder"

languagecode = "en"

googleAnalytics = "UA-128985004-3"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[blackfriday]
  hrefTargetBlank = true
  
# A redirect rule for rbind.io
[[redirects]]
  from = "https://jayachar.netlify.com/"
  to = "https://jay.rbind.io/"

  # The default HTTP status code is 301, but you can define a different one.
  status = 301

  # By default, redirects won't be applied if there's a file with the same 
  # path as the one defined in the `from` property. Setting `force` to `true` 
  # will make the redirect rule take precedence over any existing files.
  force = true  

[params]
    author = "Jay Achar"
    description = "Jay Achar's personal website"
    keywords = "blog,developer,personal"
    info = "Tuberculosis, HIV, Global Health"
    avatarurl = "images/avatar.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/JayAchar/"
#[[params.social]]
#    name = "orcid"
#    icon = "aib ai-orcid"
#    weight = 2
#    link = "https://orcid.org/0000-0002-2521-4422"
[[params.social]]
    name = "ResearchGate"
    icon = "fab fa-researchgate"
    weight = 2
    url = "https://www.researchgate.net/profile/Jay_Achar"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/jay-achar-666a7611a/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 4
    url = "https://twitter.com/dr_jay_a"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 5
    url = "https://www.instagram.com/jay_achar/"

[[menu.main]]
    name = "About"
    weight = 1
    url  = "/construction/"
[[menu.main]]
    name = "Packages"
    weight = 2
    url = "/construction/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/construction/"
[[menu.main]]
    name = "Contact"
    weight = 5
    url = "/construction/"
