---
date: "2018-12-30T22:40:04+01:00"
slug: "about"
title: "About"
---
# What do I do?

My name is Jay Achar. I am a UK-trained medical doctor with a speciality in Infectious Diseases and Internal Medicine from Australia. I have worked for [MSF UK](http://www.msf.org.uk) since 2014 as a tuberculosis (TB), HIV and viral hepatitis specialist. Aside from an emergency secondment to support the organisation during the West African Ebola outbreak, my operational attention has been predominantly on drug-resistant tuberculosis and the Eastern European and Central Asian  countries of the WHO Euro region. 

I'm passionate about access to healthcare, people-centredness and the bioethical concepts of equity and justice. In the field of TB, I work hard to improve our knowledge on the epidemiology, diagnosis and treatment of drug-resistant TB. 

In addition to my medical degree from <a href="http://www.ucl.ac.uk/" target="_blank">University College London</a>, I am also a Fellow of the <a href="https://www.racp.edu.au" target="_blank">Royal Australasian College of Physicians</a>. I was awarded a Diploma of Tropical Medicine and Hygiene (DTM&H) by the <a href="https://www.rcplondon.ac.uk" target="_blank">Royal College of Physicians</a> and have completed a MSc in Epidmiology at the <a href="https://www.lshtm.ac.uk" target="_blank">London School of Hygiene and Tropical Medicine</a>. 