---
date: "2018-12-30T22:40:04+01:00"
slug: "about"
title: "About"
description: "What do I do?"
type: "static"
---

I am a UK-trained medical doctor with a speciality in Infectious Diseases and Internal Medicine from Australia. I have worked for [MSF UK](http://www.msf.org.uk){target="_blank"} since 2014 as a tuberculosis (TB), HIV and viral hepatitis specialist. Aside from an emergency secondment to support the organisation during the West African Ebola outbreak, my operational attention has been predominantly on drug-resistant tuberculosis and the Eastern European and Central Asian countries of the WHO Euro region. Since the beginning of 2019, I have also led MSF's technical TB working group - a role that has required a greater focus on exernal relations, advocacy and global policy and research. 

I'm passionate about access to healthcare, people-centredness and the bioethical concepts of equity and justice. In the field of TB, I work hard to improve our knowledge on the epidemiology, diagnosis and treatment of drug-resistant TB. 

Aside from my clinical and epidemiological interests in TB, I am also improving my skills in data processing, analysis and visualisation. This has been a natural progression from my MSc and the frequent use of programmatic data in my current roles. 

In addition to my medical degree from <a href="http://www.ucl.ac.uk" target="_blank">University College London</a>, I am also a Fellow of the [Royal Australasian College of  Physicians](https://www.racp.edu.au){target="_blank"}. I was awarded a Diploma of Tropical Medicine and Hygiene (DTM&H) by the [Royal College of Physicians](https://www.rcplondon.ac.uk){target="_blank"} and have completed a MSc in Epidmiology at the [London School of Hygiene and Tropical Medicine](http://www.lshtm.ac.uk){target="_blank"}. 

