---
title: School Diverstiy - Tidy Tuesday
author: Jay Achar
date: '2019-09-29'
slug: tt-19-39-diversity
categories:
  - dataviz
tags:
  - R
  - tidytuesday
description: 'Submission to the weekly dataviz online community get together'
type: post
draft: true
---
```{r load, echo = FALSE, message = FALSE}
library(tidyverse)
library(lubridate)
```

After a bit of a break, I thought I'd spend a bit of time on this week's <a href="https://github.com/rfordatascience/tidytuesday" target="_blank">#TidyTuesday</a> dataset. Week 39's data comes from the National Centre for Education Statistics (NCES) in the US where private and charter schools are excluded. 

A fuller description of the data including a codebook is available <a href="https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-09-24" target="_blank">here</a>. 

# Get the data!

```{r import-data, message=FALSE}
school_diversity <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-24/school_diversity.csv")
```

Here's a quick glimpse before a more careful look: 
```{r data-glimpse}
glimpse(school_diversity)
```

```{r}
state.abb

```

