---
title: Curriculum Vitae
author: Jay Achar
date: '2019-09-08'
type: "about"
description: "Infectious disease specialist and epidemiologist with particular expertise in TB and HIV"
---
### Education

<p class="cv-header">MSc in Epidemiology</p>
<p class="cv-feature">Distinction
<p class="cv-detail">London School of Hygiene and Tropical Medicine - 2018<br>
Modules included: Advanced Statistical Methods in Epidemiology, Modelling and the Dynamics of Infectious Diseases and Epidemiology of Communicable diseases</p>

<p class="cv-header">Diploma of Tropical Medicine and Hygiene</p>
<p class="cv-detail">Royal College of Physicians, London, UK - 2017</p>

<p class="cv-header">Fellowship of the Royal Australasian College of Physicians</p>
<p class="cv-detail">Infectious Diseases</p>
<p class="cv-detail">Royal Australasian College of Physicians - 2013</p>

<p class="cv-header">MBBS in Medicine and Surgery</p>
<p class="cv-detail">University College London - 2004</p>

### Employment

<p class="cv-header">MSF International Tuberculosis Working Group Leader</p>
<p class="cv-detail">Manson Unit, M&eacute;decins Sans Fronti&egrave;res UK - 2019 to present</p>
Within this role, I take responsiblity for coordinating technical advisors for TB across the organisation, justifying and proposing the organisation's strategic direction, representing MSF in our advocacy messaging and at external meetings and committees, while also supporting colleagues on research topics, resource allocation and development of cross-sectional dossiers. 

<p class="cv-header">TB/HIV/Hepatitis and Research Programme Advisor</p>
<p class="cv-detail">Manson Unit, M&eacute;decins Sans Fronti&egrave;res UK - 2015 to present</p>
When I joined MSF, this was the job I dreamt of holding. Over the years, I've gained field experience in Belarus, Russia, Tajikistan, Uzbekistan, South Sudan, DR Congo, and Sierra Leone, mixing short strategic visits with longer more comprehensive field support. 

The job also requires justification and planning of a wider portfolio of TB across one section of MSF both through a technical medical and humanitarian lens. 

The strong implementation focus of the position requires strengths in field support, guideline development, research methodology and execution as well as important advocacy roles within policy and technical committees. 

<p class="cv-header">Ebola Advisor</p>
<p class="cv-detail">Manson Unit, M&eacute;decins Sans Fronti&egrave;res UK - 2014 to 2015</p>

<p class="cv-header">Infectious Disesases Specialist</p>
<p class="cv-detail">Alice Springs Hospital, NT, Australia and Blacktown Hospital, NSW, Australia - periodic 2014 to 2019</p>

<p class="cv-header">General Physician</p>
<p class="cv-detail">Alice Springs Hospital, NT, Australia - periodic 2014 to 2019</p>

<p class="cv-header">International field TB doctor</p>
<p class="cv-detail">M&eacute;decins Sans Fronti&egrave;res Uzbekistan - 2013</p>

<p class="cv-header">Intensive Care Registrar</p>
<p class="cv-detail">St Vincent's Hospital, Victoria, Australia - 2012 to 2013</p>

<p class="cv-header">Infectious Diseases Registrar</p>
<p class="cv-detail">Monash Medical Centre, Royal Melbourne Hospital and St Vincent's Hospital, Victoria, Australia - 2009 to 2012</p>

### Publications
#### Peer-reviewed

See my <a href="https://orcid.org/0000-0002-2521-4422" target="_blank">ORCID record</a> for a full list of my peer-reviewed publications. 

#### Conference abstracts

**Achar J**. Treatment responses in childhood DR-TB. Is poor treatment the problem? Oral presentation at the European Society of Paediatric Infectious Diseases conference, Slovenia, 2019

Sinha A, Tassew Y, Khusainova M, **Achar J** et al. Effectiveness of TB treatment regimens containing bedaquiline with repurposed drugs for drug resistant tuberculosis patients in Chechnya Republic, Russian Federation. F1000Research 2017, 6:650; available <a href="http://dx.doi.org/10.7490/f1000research.1114040.1" target="_blank">here.</a>  

Kuhlin J, Smith C, Khaemraev A, **Achar J** et al. The impact of pyrazinamide resistance upon the treatment outcome of patients with multidrug-resistant tuberculosis in Karakalpakstan, Uzbekistan F1000Research 2017, 6:651; available <a href="http://dx.doi.org/10.7490/f1000research.1114041.1" target="_blank">here.</a>   

Morales AM, Pylepenko T, Fiori A, **Achar J**, et al. Lessons Learned from 2014 to 2017 in the Diagnosis and Treatment with Direct Acting Antivirals of Hepatitis C in co-Infected HIV/HCV Patients at the Tashkent AIDS Center, Uzbekistan. Poster presentation at The 16th European AIDS conference, 2017, Milan, Italy

**Achar J**, et al. Short-course MDR-TB treatment compared with standard of care in
Uzbekistan: culture conversion rates after 2 months. Oral abstract presentation at The Union Conference 2016, Liverpool, UK

Trauer J, **Achar J**, et al. Modelling the effect of short-course multidrug-resistant TB treatment in Karakalpakstan, Uzbekistan. Poster at The Union conference 2016, Liverpool UK. Available <a href="https://f1000research.com/posters/5-2751" target="_blank">here.</a>

Gayton I, **Achar J**, Greig J, et al. Tablet-based clinical management tool: building technology for Ebola management centres. Presentation at: MSF Scientific Day 2015, London. Available <a href="http://f1000research.com/slides/1000072" target="_blank">here.</a>  

**Achar J**, Spelman DW, Jenney AWJ, Buising KL, Rowland M et al. Aspergillus endocarditis: A review of eleven cases from the International Collaboration on Endocarditis (ICE) – Poster presented at ISCVID, Cairns 2011

#### Blogs
<a href="https://bit.ly/2FDQBKE" target="_blank">Progress in Peril: Stagnant Funding Could Lengthen the TB Elimination Timeline.</a> PLoS Speaking of Medicine blog, 2019.

<a href="https://blogs.bmj.com/bmj/2016/03/24/drug-resistant-tuberculosis-not-just-a-precursor-to-the-post-antibiotic-apocalypse/" target="_blank">Drug resistant tuberculosis—not just a precursor to the post-antibiotic apocalypse.</a> BMJ Opinion, 2016.

### Honorary positions

<p class="cv-header">New Diagnostics Working Group</p> 
<p class="cv-detail">Stop TB Partnership - 2019</p> 

<p class="cv-header">Regional Green Light Committee Member</p> 
<p class="cv-detail">World Health Organisation Europe, Copenhagen - 2017 to present</p> 

<p class="cv-header">European Tuberculosis Research Initiative member</p> 
<p class="cv-detail">World Health Organisation Europe, Copenhagen - 2017 to present</p> 

<p class="cv-header">MSF Denmark Board of Directors</p> 
<p class="cv-detail">Co-opted international member - 2017 to 2019</p> 

<p class="cv-header">endTB clinical trial medical review committee member</p> 
<p class="cv-detail">2016 to present</p> 

<p class="cv-header">TB-PRACTECAL clincial trial steering committee member</p> 
<p class="cv-detail">2017 to present</p> 

<p class="cv-header">Academic reviewer</p> 
<p class="cv-detail">International Journal of Tuberculosis and Lung Disease, Clinical Infectious Diseases, Emerging Infectious Diseases, annual Union Conference against TB and Lung Disease - 2016 to present</p> 

### Research skills

<p class="cv-header">R statistical software</p>
<p class="cv-detail">Self-taught to facilitate transparent and reproducible statistical analysis for healthcare research. Two packages developed for internal analysis of routine programme data - <a href="https://jayachar.github.io/tbcleanr/" target="_blank">tbcleanr</a> and <a href="https://jayachar.github.io/tbgeneratr/" target="_blank">tbgeneratr</a>.</p> 

<p class="cv-header">Statistics</p>
<p class="cv-detail">Far from being a medical statistician, this is an area of interest with plenty of self-learning. Two advanced modules in medical statistics during the MSc in Epidemiology has been followed up with more work on missing data, more advanced regression modelling, further practice with paired data and time-series data.</p>

<p class="cv-header">GCP qualified</p>
<p class="cv-detail">Certificates attained in 2014, 2016 and 2019.</p>



